# Generated by Django 5.0.6 on 2024-08-23 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_factorywarehouse_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factory_users', to='core.factory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('factory', 'user')},
            },
        ),
    ]
