# Generated by Django 5.0.6 on 2024-08-26 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factorywarehouse',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
    ]
