# Generated by Django 5.0.6 on 2024-08-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_factorywarehouse_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factoryproducts',
            name='factory',
        ),
        migrations.RemoveField(
            model_name='factoryproducts',
            name='product',
        ),
        migrations.AlterUniqueTogether(
            name='factoryuser',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='factoryuser',
            name='factory',
        ),
        migrations.RemoveField(
            model_name='factoryuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='productorderdelivery',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='productorderdelivery',
            name='product_order',
        ),
        migrations.RemoveField(
            model_name='salepointproductorder',
            name='product_order',
        ),
        migrations.RemoveField(
            model_name='salepointproductorder',
            name='sale_point',
        ),
        migrations.RemoveField(
            model_name='salepointuser',
            name='sale_point',
        ),
        migrations.RemoveField(
            model_name='salepointuser',
            name='user',
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='carriers',
            field=models.ManyToManyField(blank=True, related_name='users', to='core.carrier'),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='factories',
            field=models.ManyToManyField(blank=True, related_name='users', to='core.factory'),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='sale_points',
            field=models.ManyToManyField(blank=True, related_name='users', to='core.salepoint'),
        ),
        migrations.AddField(
            model_name='factory',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='factories', to='core.product'),
        ),
        migrations.AddField(
            model_name='productorder',
            name='deliveries',
            field=models.ManyToManyField(blank=True, related_name='product_orders', to='core.delivery'),
        ),
        migrations.AddField(
            model_name='salepoint',
            name='product_orders',
            field=models.ManyToManyField(blank=True, related_name='sale_points', to='core.productorder'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1),
        ),
        migrations.DeleteModel(
            name='CarrierUser',
        ),
        migrations.DeleteModel(
            name='FactoryProducts',
        ),
        migrations.DeleteModel(
            name='FactoryUser',
        ),
        migrations.DeleteModel(
            name='ProductOrderDelivery',
        ),
        migrations.DeleteModel(
            name='SalePointProductOrder',
        ),
        migrations.DeleteModel(
            name='SalePointUser',
        ),
    ]
