# Generated by Django 5.0.6 on 2024-09-03 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_factoryproducts_factory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productorder',
            old_name='amount',
            new_name='quantity',
        ),
    ]
