# Generated by Django 5.0.6 on 2024-09-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_amount_productorder_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factorywarehouse',
            old_name='amount',
            new_name='quantity',
        ),
        migrations.AlterField(
            model_name='productorder',
            name='order_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
