# Generated by Django 5.0.6 on 2024-09-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_amount_factorywarehouse_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
