# Generated by Django 5.0.6 on 2024-09-08 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_salepoint_product_orders_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='delivery_cost',
            new_name='cost',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='date',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='priority',
        ),
    ]
