# Generated by Django 5.0.6 on 2024-09-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_delivery_cost_delivery_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
